"""add gradcam_path and ai_explanation to reports

Revision ID: 0be1b00eabb8
Revises: f9e49a82da52
Create Date: 2026-09-29 18:44:20.533529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0be1b00eabb8'
down_revision: Union[str, Sequence[str], None] = 'f9e49a82da52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('gradcam_path', sa.String(), nullable=True))
    op.add_column('reports', sa.Column('ai_explanation', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'ai_explanation')
    op.drop_column('reports', 'gradcam_path')
    # ### end Alembic commands ###
