"""add medical_documents table

Revision ID: 82d336408f7b
Revises: 0be1b00eabb8
Create Date: 2026-09-29 19:06:16.507454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82d336408f7b'
down_revision: Union[str, Sequence[str], None] = '0be1b00eabb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('findings_json', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_documents_id'), 'medical_documents', ['id'], unique=False)
    op.create_index(op.f('ix_medical_documents_owner_id'), 'medical_documents', ['owner_id'], unique=False)
    op.create_index(op.f('ix_medical_documents_patient_id'), 'medical_documents', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medical_documents_patient_id'), table_name='medical_documents')
    op.drop_index(op.f('ix_medical_documents_owner_id'), table_name='medical_documents')
    op.drop_index(op.f('ix_medical_documents_id'), table_name='medical_documents')
    op.drop_table('medical_documents')
    # ### end Alembic commands ###
